services:
  slowmode-engine:
    image: ${DOCKERHUB_NAMESPACE:?Set DOCKERHUB_NAMESPACE in the root .env file}/nio-slowmode-engine:${IMAGE_TAG:-latest}
    build:
      context: ./services/slowmode-engine
      dockerfile: Dockerfile
    container_name: nio-slowmode-engine
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - RUST_LOG=info

  anomaly-engine:
    image: ${DOCKERHUB_NAMESPACE:?Set DOCKERHUB_NAMESPACE in the root .env file}/nio-anomaly-engine:${IMAGE_TAG:-latest}
    build:
      context: ./services/anomaly-engine
      dockerfile: Dockerfile
    container_name: nio-anomaly-engine
    restart: unless-stopped
    ports:
      - "50051:50051"
    environment:
      - RUST_LOG=info

  nio-server:
    image: ${DOCKERHUB_NAMESPACE:?Set DOCKERHUB_NAMESPACE in the root .env file}/nio-server:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: nio-server
    restart: unless-stopped
    ports:
      - "3002:3002"
    depends_on:
      slowmode-engine:
        condition: service_started
      anomaly-engine:
        condition: service_started
    env_file:
      - ./apps/server/.env
    environment:
      - SLOWMODE_ENGINE_URL=http://slowmode-engine:3003
      - ANOMALY_ENGINE_URL=anomaly-engine:50051
      - NODE_ENV=production

  nio-client:
    image: ${DOCKERHUB_NAMESPACE:?Set DOCKERHUB_NAMESPACE in the root .env file}/nio-client:${IMAGE_TAG:-latest}
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    container_name: nio-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - nio-server
    environment:
      - BACKEND_URL=http://nio-server:3002
      - NODE_ENV=production


  db:
    image: postgres:16-alpine
    container_name: postgres-prod
    restart: always
    environment:
      POSTGRES_USER: nio
      POSTGRES_PASSWORD: nio-server
      POSTGRES_DB: nio-db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - private
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atlsd -d core"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: